language: generic

sudo: false

cache:
  directories:
    - $HOME/.npm

jobs:
  include:
    - stage: build
      if: branch = webpack AND type = push
      install:
        - npm i -g npm@6.1.0
        - cd js && npm ci
      script:
        - npm run build
      after_success:
        - cd ..
      deploy:
        provider: pages
        skip-cleanup: true
        github-token: $GITHUB_TOKEN
        target-branch: webpack
        keep-history: true
        committer-from-gh: true
        verbose: true
        on:
          branch: webpack
