language: generic

sudo: false

env:
  # Define GH_USER_EMAIL & GH_USER_NAME env variables used by travis-scripts package
  - secure: "jHc1iNkaGs1Ni0BqrzXuVtsbf8L+HUqYD/p+6DgYt0wZToCxutpuRIrgjrWaPGZItJGUIqnnT/Q484V1Zcnz+WIieYBtZ9tGG8pYpz3cXJtUHH23ng+UA2okobF8410jK0jS9EyVtPAlAhFFQd0S/QijzHN6TO0Rbuwa748HslHfPNB1RSJlJ4IUGC6ikd6l+1h94tS19L9BVB07bif3wMl9E6+EyTi7yx5PEcafGlgFTP4VKXzOpSJ5JbkLnqexBr4qNV00LXd7so9EDNjCVi6cc9h92yOo8UTfX/B0yhhOUjqFpGMPKv4AU9NrkEcsMQM4U2TDpGZaWnddXoCrS1/t4oLbX1XC+5LoL5N0a3iDYn2X73Gu5DUeRa8BXkh+xM5yCxUCNj/gVB/cO61/8MObTN7eFzXfoxjgnrSRMno3aJ0o8FMZGWvgJAUFELWTJxgkU2k79+GQSTEQjTshxNuTDAJxrwDbvrd0vQrsLiCls1GWAMuVs2Tns234NLUoalms3HWkWD8tUH+vmML5UBPw+gGmNWCiByWaqKaPKz1+asRP/7ngJsTUEQvYEi4sJ2l6g/uSdH6vQuabl2/loLptZfYjtgWQe1fJaFgoFqUA386BB9WpO53DtDHHzlu30UK4wKtMwbyoZnPIfivVosqOgCMbiU5xwkbpuMPl5Nw="

cache:
  directories:
    - $HOME/.npm

jobs:
  include:
    # Bundle and commit JS
    - stage: build
      if: branch = webpack AND type = push
      install:
        - npm i -g npm@6.1.0
        - cd js && npm ci
      script:
        - npm run build -- --progress=false
      after_success:
        - $(npm bin)/set-up-ssh --key "$encrypted_e0713a64e02e_key" --iv "$encrypted_e0713a64e02e_iv" --path-encrypted-key "../.deploy.enc"
        - $(npm bin)/commit-changes --commands "true" --commit-message "Bundled output for commit $TRAVIS_COMMIT [skip ci]" --branch "webpack"
