language: generic

sudo: false

env:
  # Define GH_USER_EMAIL & GH_USER_NAME env variables used by travis-scripts package
  - secure: "ssI+cNz39USMm6EehqXvpO0r7M3joBLh8JiyYV1FhgA7bKaEKWdAMQ8eWaC9h8N0A45/hEFNHSV7AkuxSwM9UwlEgMjwPBup7Easzsbr+cYvIeFTRtBfq7FV0N3sc4rk3YUvikYe4EA0kQrQA3fT50Uie8oRoWyLghQEVy0i7GlWIMF6jLxkFIQy8jOFud3z6YAe4AvrudiIGf9BTgeU6NYIsJ3bNYhPQ1UNv4cORohGZwKfpYynfVS4CoEr3dihz0TcZuoOnECkMCai635lzQILr3hUxTLURQL3+rzQHattPlUL+b9Zd9jw3OPrIwVEeqx9Si+TaTXOqWeHB2Ul395goc5Y3+ATKXk0EA4E/0T4gKvYeLIKs12S1xAx9uMX8SDbIlLL9p4LGrh9BjmsQvM6L0qS5TmRNVTxpap6iIPOmzRIrXFa0MuBIgyJSsWAOgRZAtUOnGS4TPadc/UWECvtoLxz3oDauDh0c1Z6tstSM1Rg2/Kabj+x/PvVASduFh+TMfH2vAHSRdo19go/S7ou+25yLqOopY0L7aBAZPeWQJlifQSvuZfPtkUVCWpuJXffB9x5VYlUpkmDui2eMLs2xcHH4GPLthqe6eX7b1Js6IiReSU/Zrw6ty85XF6pj2vS8+1G+EqPAiUdQ0/KaCLFKNq2klfUzJLEzW6OcIU="

cache:
  directories:
    - $HOME/.npm

jobs:
  include:
    # Bundle and commit JS
    - stage: build
      if: branch = webpack AND type = push
      install:
        - npm i -g npm@6.1.0
        - cd js && npm ci
      script:
        - npm run build -- --progress=false
      after_success:
        - $(npm bin)/set-up-ssh --key "$encrypted_e0713a64e02e_key" --iv "$encrypted_e0713a64e02e_iv" --path-encrypted-key "../.deploy.enc"
        - $(npm bin)/commit-changes --commands "true" --commit-message "Bundled output for commit $TRAVIS_COMMIT [skip ci]" --branch "webpack"
