language: generic

sudo: false

env:
  global:
    # Define GH_USER_EMAIL & GH_USER_NAME env variables used by travis-scripts package
    - secure: "nr0oQSKnC2xod3pUqDWid7/fa+citbAdxrQyQTMfRIcAa6o3BKgKHh9efW9qYIbApb16zo7LioDX3PIE8IHk3hqISI1xFgY7MNBejxofJ5hpjIwgPkqQ8YuokamYlLM+2cxn+w32ZQSs30ICTIHbxJleYc0zrkojdF2fTvEUzN78el9oZLUjo/r7FWfdBp0knaPxWtVPNqUa33AnLkxYOFkFqlCk49v/NmSd0QqmjCW57cSRHWARkCiPA6qUd2obw9dHIAbQUz6A262MfqOuZ3xjQmYteAv4SkSz5l3ee2vRhuJ3RTY8SaVXajWfAUZOVlnzVJVQfjU6QcjsvWIEfFWb3psA0yWbDVfE63DWtmaPu6Li/th42vZxe0JciNNCS96CBnOaufSkyYKzTcpKx0AivNPrEjlVYJUAdeA2WtVJhfiFo2WzcLepQF2AthJT2AOSeNQSLoVzLwwbZUmu7Jv5ujTN1OMkPWdXcIXWz46rD5+aF6FBogB+u0tPOu4a0qULexv9GBXPCP3NYYy82Luf9JcgYTodmngRN+CuMajtusJS1Kue+yaxb/LHOnYqH2eezaESqTpmLnVvmhcbOgV/v93WbK3HilxCxZTcLQV3FctVdmijb2lAA9IJe3hvKagPSY5wp60o65eKp8IZRwvnM4nX264ZrYMOfGUXol8="

cache:
  directories:
    - $HOME/.npm

jobs:
  include:
    # Bundle and commit JS
    - stage: build
      if: branch = webpack AND type = push
      install:
        - npm i -g npm@6.1.0
        - cd js && npm ci
      script:
        - npm run build -- --progress=false
      after_success:
        - $(npm bin)/set-up-ssh --key "$encrypted_e0713a64e02e_key" --iv "$encrypted_e0713a64e02e_iv" --path-encrypted-key "../.deploy.enc"
        - $(npm bin)/commit-changes --commands "true" --commit-message "Bundled output for commit $TRAVIS_COMMIT [skip ci]" --branch "webpack"
