language: generic

sudo: false

env:
  global:
    # Define GH_USER_EMAIL & GH_USER_NAME env variables used by travis-scripts package
    - secure: "Eo9WiYTl7Jk2VA3xnQBmvd1Xtly5NXYzQFjMVgl9g9s6giMUw78xQ/LfFWa7YJCmfh4SNePHYnDEpyiOwjtzNq1hox/dzhgTTCQaovxudLUVPv9izp39PyVpC7utHn3MuDqVEpZpoHhGnhRDX59Gfk8ZYE6pI2mddJlT6NXdUqiND9CuTtH9XWA9IkwAtnccX2XctLdjXr5v9k73o2lub6vgBar5VOhEcewAolaqq/7q0gcO/Otqd1hAG/Dim5inBMRpKnrXeA3LcHyE7f28mQo11/F0RXM902kdM+gBMoj1kDfF+8Mw8GmiCmTyKYTuvJ6lb514YR+pm+bCcNx/y1No6iPvV7EmtmpK7twfgX3KYz4RZXibJHs/D1yQ8PJkQRE+NpmXhL84UydJJwOedfsSUJ9ZsSHUNvrhpQFC8T/ig1eHd0lU4VBJ7TzOm0iBGGAEHGshu6t/afoHgKrw/A3i3HZON/h24fkRUhcuWrGMN356rDykX0+KZB0kTNDOB4HNyOs7+NZaw/Xl0PwkJ4ar4jv2UmptBpIZ7CQpaWA9QPbX43dPDJqYgOcuFYjJrsRcJlXvfzH6AWqf7zF/gJpX74lQXXqSf55ml4k5VXPW+RpdTqaWjji0mUi7Az6e3Wmm4bYZhkim3OnARKg6xylT4EOLHY9hTkZ2K/XM2Rc="

cache:
  directories:
    - $HOME/.npm

jobs:
  include:
    # Bundle and commit JS
    - stage: build
      if: branch = webpack AND type = push
      install:
        - npm i -g npm@6.1.0
        - cd js && npm ci
      script:
        - npm run build -- --progress=false
      after_success:
        - $(npm bin)/set-up-ssh --key "$encrypted_e0713a64e02e_key" --iv "$encrypted_e0713a64e02e_iv" --path-encrypted-key "../.deploy.enc"
        - $(npm bin)/commit-changes --commands "true" --commit-message "Bundled output for commit $TRAVIS_COMMIT [skip ci]" --branch "webpack"
