language: generic

sudo: false

env:
  global:
    # Define GH_USER_EMAIL & GH_USER_NAME env variables used by travis-scripts package
    - secure: g/JgEwlkks8GjuSz2BnR8ObigDYSCipXXD4kODIbw3I5usAMpv5GxkCYbWk5Ih0dWWlji/t3rSMGtK4XPsYdd4E6YabczvyDTjFkkjoLN8BQnw8DBvFvKjYWOqC/hcdVCw1qhDGT28RCmIwERgmoVHSENjdBV2NMOWISeMeyZr0oK8Tf60aM5A+qhG8Nglqv7iHGdhUUHx0dIsLAfsH3Uu0QqYH03azVPO9AkdWVrInUZA2njGuyQc+h2aWPBs8+GcSQmWWcmluGpdsnIXGrIEKt/nOiQ/q4yFvMv+E/DpW9X8P6wKUBdMpUvWhn56wvWT0/1x3ywtYmEBCqiIjFMCybGbfxX0yCXORc10/LSDIjKSNodA+M6Mfe7KlbXN9lL0g79cW00g19a69tvZaaEQ7p3hC6YwRoEJbs9HhGi5qbNNJOh+VUKeEd9DCymigpISA7tmXQhzkGcowXoyywr5J9Z7VwX9B1xw7s4Y8Ap8saL854f1HZtyfJid9OluNuYwmutgBz3pCgOkPwYjI+xuBujQmKcuXFx1WeaYRIGj2P0lWYMV0x68GyK1F4IFLRO1I8QXcmVGs5ulUCt6LNJPr0TFgSPkSJYAq8MMYalMwUdcOemsZfY/5QY26tYbiwdz13+XF80xWC3kQebqjClU4zLwW5nyDr+Ka1xH29wW0=

cache:
  directories:
    - $HOME/.npm

jobs:
  include:
    # Bundle and commit JS
    - stage: build
      if: branch = webpack AND type = push
      install:
        - npm i -g npm@6.1.0
        - cd js && npm ci
      script:
        - npm run build -- --progress=false
      after_success:
        - $(npm bin)/set-up-ssh --key "$encrypted_e0713a64e02e_key" --iv "$encrypted_e0713a64e02e_iv" --path-encrypted-key "../.deploy.enc"
        - $(npm bin)/commit-changes --commands "true" --commit-message "Bundled output for commit $TRAVIS_COMMIT [skip ci]" --branch "webpack"
